### ISSUE TITLE
Volume buttons not working to snap photo. feature-missing

### ISSUE THREAD

**Issue by Haunter** [kb1ooo/snappy-public#3]
The volume buttons are not working to snap photos regardless of Snappy being activated from the lockscreen or springboard.

**Comment by kb1ooo** [comment]
On Mon, Dec 19, 2011 at 02:03:05PM -0800, Haunter wrote:

> The volume buttons are not working to snap photos regardless of Snappy being activated from the lockscreen or springboard.

Thanks.  Works for me from the lock screen though (at least from the ear
buds, my vol up button is broken on my 3gs).

**Comment by Haunter** [comment]
Neither up nor down worked for me. Do not have a headset with volume control either to test. Could be a possible conflict with biteSMS?

**Comment by kb1ooo** [comment]
Hi,

I installed bitesms late lastnight and the lockscreen problem appears to
be exclusively a bitesms issue.  I.e. volume shutter will fail from the
lockscreen regardless of whether or not Snappy is installed. 

It seems that the act of installing bitesms breaks the volume button
from being used to snap pictures from the lockscreen as it's still
broken even after removing bitesms.  It must set some setting somewhere
because I have to turn off the SBSettings plugin in order for the
functionality to come back.

I'll be trying to figure more out today, but I did fix the missing
volume shutter when unlocked.  

Best,
Marc
